### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by matzl** [makejs/inkscape-laser#1]
Hello,
First of all: Thanks for all the work and the tutorial! It is a great help.
However, i realized, that there's an error on both the horizontal g.code tool and the J Tech Photonics Laser Tool when I follow your steps with the horizontal cloned lines. Right after I click Generate, I get a message box with that message:
```
Traceback (most recent call last):
  File "laserHorizontal.py", line 3253, in <module>
    e.affect()     
  File "C:\Users\Matthias\Portable Apps\inkscape\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "laserHorizontal.py", line 3237, in effect
    self.orientation( self.layers[min(0,len(self.layers)-1)] )        
  File "laserHorizontal.py", line 3166, in orientation
    doc_height = self.unittouu(self.document.getroot().xpath('@height', namespaces=inkex.NSS)[0])
IndexError: list index out of range
```
Any idea where it comes from? i used to use the J Tech Photonics Laser Tool but now it doesn't work as well, even if I want to laser a simple rectangle (although I would like to laser a structure with 500+ lines).

**Comment by marc9876** [comment]
I'm having the same problem. any updates to this?

**Comment by makejs** [comment]
Just seen these. Ill take a look and see what I can do.

**Comment by makejs** [comment]
I'm assuming your Inkscape is later than 0.91? If you revert back it should work. I will let you know if I get this figured out but might be a while.

**Comment by makejs** [comment]
So I just updated to the latest and do not get this error. There is an issue where inkex requires lxml and its not getting it because of a bad install or update. See [here](https://inkscape.org/en/learn/faq/#fantastic-lxml-wrapper-libxml2-required-inkexpy-and-therefore-extension). So make sure you completely remove old version of inkscape then install the new version. Hopefully this helps.

**Comment by marc9876** [comment]
Hi Cale. Thanks for replying. I'll give that you suggest a try.
Regards

Jodee
